--- 
- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present

- name: Start and enable PostgreSQL service
  systemd:
    name: postgresql
    state: started
    enabled: yes

- name: Run PostgreSQL container
  command: >
    docker run -d --name postgresdb
    -e POSTGRES_USER=voting_user
    -e POSTGRES_PASSWORD=voting_password
    -e POSTGRES_DB=voting_db
    -p 5432:5432
    postgres:latest