---
- name: Install .NET 7 SDK on backend instance_b
  hosts: jke_redisWorker
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name:
          - wget
          - apt-transport-https
        state: present

    - name: Download Microsoft package repo
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb

    - name: Install Microsoft package repo
      apt:
        deb: /tmp/packages-microsoft-prod.deb

    - name: Install .NET SDK
      apt:
        name: dotnet-sdk-7.0
        state: present
        update_cache: yes
